'use client'

import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header/Header";
import Menu  from "./_components/Menu/Menu";

import AuthProvider from "./_components/Context/AuthContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AuthProvider>
          <Header />
          <Menu />
          {children}
        </AuthProvider>
      </body>

    </html >
  );
}
